[package]
name = "neon-project"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_project"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
neon-runtime = "0.1.22"
sourcemap = "*"
